"""initial schema

Revision ID: 86aa2d3d6c4b
Revises: 
Create Date: 2026-02-09 16:15:07.029219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86aa2d3d6c4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('criteria_type', sa.Enum('streak_days', 'tasks_completed', 'projects_completed', 'custom', name='criteriatype'), nullable=False),
    sa.Column('criteria_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('badge_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rit_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('student', 'faculty', 'admin', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('research_projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('faculty_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planning', 'in_progress', 'submitted', 'completed', 'archived', name='projectstatus'), nullable=False),
    sa.Column('main_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_supervisor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('streak_events',
    sa.Column('streak_event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('streak_started', 'streak_extended', 'streak_broken', 'badge_earned', name='streakeventtype'), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('streak_event_id')
    )
    op.create_table('streak_snapshots',
    sa.Column('streak_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('did_research_activity', sa.Boolean(), nullable=False),
    sa.Column('research_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('streak_id')
    )
    op.create_table('tia_profiles',
    sa.Column('tia_profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('tone', sa.Enum('formal', 'casual', 'encouraging', 'critical', 'humorous', name='tone'), nullable=False),
    sa.Column('expertise_area', sa.String(length=150), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('tia_profile_id')
    )
    op.create_table('user_badges',
    sa.Column('user_badge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.badge_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_badge_id')
    )
    op.create_table('user_streak_status',
    sa.Column('user_streak_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_streak_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tia_profile_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.project_id'], ),
    sa.ForeignKeyConstraint(['tia_profile_id'], ['tia_profiles.tia_profile_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('project_faculty',
    sa.Column('project_faculty_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('faculty_user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('supervisor', 'reviewer', 'reader', name='facultyrole'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.project_id'], ),
    sa.PrimaryKeyConstraint('project_faculty_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('reading', 'writing', 'analysis', 'meeting', 'admin', 'other', name='tasktype'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'done', 'overdue', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='taskpriority'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.project_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('user', 'tia', 'professor', name='sendertype'), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_role', sa.Enum('user_query', 'tia_reply', 'professor_reply', 'system_note', name='messagerole'), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('is_visible_to_user', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('tasks')
    op.drop_table('project_faculty')
    op.drop_table('conversations')
    op.drop_table('user_streak_status')
    op.drop_table('user_badges')
    op.drop_table('tia_profiles')
    op.drop_table('streak_snapshots')
    op.drop_table('streak_events')
    op.drop_table('research_projects')
    op.drop_table('users')
    op.drop_table('badges')
    # ### end Alembic commands ###
